# Generated by Django 5.1.7 on 2025-03-18 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_alter_contactmodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,2}\\s?)?1?\\-?\\.?\\s?\\(?\\d{3}\\)?[\\s.-]?\\d{3} [\\s.-]?\\d{4}$', 'Enter a valid 10-digit phone number')]),
        ),
    ]
